[default]
contracts = 'contracts'  # The source directory
libs = ['modules']       # A list of library directories
solc_version = '0.8.7'   # Override for the solc version (setting this ignores `auto_detect_solc`)
offline = true           # Disable downloading of missing solc version(s)
optimizer = true         # Enable or disable the solc optimizer
optimizer_runs = 200     # The number of optimizer runs
verbosity = 2            # The verbosity of tests
bytecode_hash = "none"   # For deterministic code

[local]
fuzz_runs = 100

[deep]
fuzz_runs = 1000

[super_deep]
fuzz_runs = 30000
