name: Static Analysis
on:
  push:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo snap install solc
          python -m pip install --upgrade pip
          pip install slither-analyzer==0.8.2 solc-select==0.2.1
          solc-select install 0.8.7
          solc-select use 0.8.7

      - name: Checkout mpl-migration submodule
        env:
          SSH_KEY_MPL_MIGRATION: ${{secrets.SSH_KEY_MPL_MIGRATION}}
        shell: bash
        run: |
          mkdir $HOME/.ssh
          echo "$SSH_KEY_MPL_MIGRATION" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          git submodule update --init --recursive modules/mpl-migration

      - name: Checkout revenue-distribution-token submodule
        env:
          SSH_KEY_RDT: ${{secrets.SSH_KEY_RDT}}
        shell: bash
        run: |
          rm -rf $HOME/.ssh/id_rsa
          echo "$SSH_KEY_RDT" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          git submodule update --init --recursive modules/revenue-distribution-token

      - name: Summary of static analysis
        run: |
          slither contracts --print human-summary

      - name: Contract summary of static analysis
        run: |
          slither contracts --print contract-summary

      - name: Function summary
        run: |
          slither contracts --print function-summary

      - name: Inheritance
        run: |
          slither contracts --print inheritance

      - name: Data dependency
        run: |
          slither contracts --print data-dependency

      - name: Static Analysis
        run: |
          slither contracts
        continue-on-error: true
